---
- hosts: localhost
  vars:
    region: 
    vpc_id:
  tasks:
          - name: Gather security groups
            amazon.aws.ec2_group_info:
              region: "{{ region }}"
            register: value
          
          - name: Write Temp File
            set_fact:
                payload: "{{ payload|default([]) + [ [item.group_id] + [item.group_name] + [item.description] ] }}"
            loop: "{{ value.security_groups  }}"

          - debug:
              var: payload

          - name: example using security group rule descriptions
            amazon.aws.ec2_group:
              name: "{{ item.1 }}"
              region: "{{ region }}"
              vpc_id: "{{ vpc_id }}"
              group_id: "{{ item.0 }}"
              description: "{{ item.2 }}"
              purge_rules: no
              rules:
                - proto: tcp
                  ports:
                  - "9100"
                  cidr_ip: x.x.x.x/32
                  rule_desc: allow prometheus to access metrics
            loop: "{{ payload }}"
